-- return {
--   "sontungexpt/sttusline",
--   branch = "table_version",
--   dependencies = {
--     "nvim-tree/nvim-web-devicons",
--   },
--   event = { "BufEnter" },
--   config = function()
--     vim.opt.laststatus = 3
--     local components = require("utils.sttusline")
--
--     require("sttusline").setup({
--       statusline_color = "StatusLine",
--       disabled = {
--         filetypes = {
--           "NvimTree",
--         },
--         buftypes = {
--           "terminal",
--         },
--       },
--       components = {
--         "mode",
--         "filename",
--         "git-branch",
--         "git-diff",
--         components.navic,
--         "%=",
--         components.dap,
--         "diagnostics",
--         components.macro_recording,
--         "lsps-formatters",
--         "pos-cursor",
--       },
--     })
--   end,
-- }

-- return {
--   "sontungexpt/witch-line",
--   dependencies = { "nvim-tree/nvim-web-devicons" },
--   lazy = false,
--   config = function()
--     local colors = require("utils.colors")
--     require("witch-line").setup({
--       --- @type CombinedComponent[]
--       statusline = {
--         global = {
--           "mode",
--           "file.icon",
--           "file.name",
--           "file.modifier",
--           "git.branch",
--           "git.diff.added",
--           "git.diff.removed",
--           "git.diff.modified",
--           "%=",
--           {
--             id = "macro_recording",
--             events = { "RecordingEnter", "RecordingLeave" },
--             style = { fg = colors.red },
--             update = function()
--               local recording_register = vim.fn.reg_recording()
--               if recording_register and recording_register ~= "" then
--                 return "Recording @" .. recording_register
--               end
--               return nil
--             end,
--           },
--           "diagnostic.error",
--           "diagnostic.warn",
--           "diagnostic.hint",
--           "diagnostic.info",
--           "copilot",
--           "nvim_dap",
--           "lsp.clients",
--           "encoding",
--           "cursor.pos",
--         },
--       },
--       cache = { enabled = false },
--       disabled = {
--         filetypes = { "NvimTree" },
--         -- buftypes = { "terminal" },
--       },
--       auto_theme = true,
--     })
--   end,
-- }

return {
  "nvim-mini/mini.statusline",
  version = false,
  opts = {},
}
